name: Go
on: [push]
jobs:

  build:
    name: Build on node ${{ matrix.go_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: [1.10, 1.11, 1.12, 1.13]
        os: [ubuntu-latest, macOS-latest]
        
    steps:
    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go_version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: |
        mkdir -p ./build
        go build -v ./cmd/options-gen -o ./build
   
    - name: Test
      run: go test -v ./...   
